package fr.killiandev.book.observability.api.exception;

public enum ExceptionType {
    ENTITY_NOT_FOUND,
    INVALID_ROLE,

    AUTH_CONSTRAINT_ERROR,
    AUTH_INTERNAL_LINK_ERROR,
    AUTH_ALREADY_LINKED_ERROR,
    AUTH_GENERATE_CODE_ERROR,

    SUPABASE_UNKNOW_ERROR,
    SUPABASE_RATE_LIMIT_ERROR,
    SUPABASE_INVALID_JWT,

    S3_STORAGE_ERROR,
    S3_FIND_ERROR,

    PROFILE_INVALID_AVATAR_FILE_ERROR,
    PROFILE_INVALID_AVATAR_FILE_TYPE_ERROR,
    PROFILE_ALREADY_EXISTS_ERROR,

    GUIDE_INVALID_OWNER_ERROR,
    GUIDE_INVALID_SLUG_ERROR,
    GUIDE_INVALID_AI_RESPONSE_ERROR,

    SCRAPING_INVALID_URL_ERROR,
    SCRAPING_INVALID_HTML_ERROR,
    SCRAPING_INVALID_JSON_ERROR,
    SCRAPING_INVALID_JSON_EXTRACT_ERROR,

    MAP_API_ERROR,

    QUESTION_NOT_ACTIVE_ERROR,
    QUESTION_ALREADY_ANSWER_ERROR,
    QUESTION_INVALID_ANSWER_ERROR,

    CONSTRAINT_VIOLATION_ERROR,
    ;
}
