CREATE TABLE book.housing
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    profile_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_housing PRIMARY KEY (id)
);