CREATE TABLE book.profile_answer
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    answer_value     VARCHAR(255)                            NOT NULL,
    profile_id       BIGINT                                  NOT NULL,
    question_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_profileanswer PRIMARY KEY (id)
);

ALTER TABLE book.profile_answer
    ADD CONSTRAINT FK_PROFILEANSWER_ON_QUESTION FOREIGN KEY (question_id) REFERENCES book.question (id);