CREATE TABLE book.guide
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at       TIMESTAMP WITHOUT TIME ZONE,
    language               VARCHAR(255)                            NOT NULL,
    slug                   TEXT                                    NOT NULL UNIQUE,
    general_info           JSONB,
    wifi_info              JSONB,
    rules_info             JSONB,
    transportation_info    JSONB,
    restaurants            JSONB,
    attractions            JSONB,
    emergency_contacts     JSONB,
    appliance_instructions JSONB,
    custom_categories      JSONB,
    housing_id   BIGINT,
    CONSTRAINT pk_guide PRIMARY KEY (id)
);

ALTER TABLE book.guide
    ADD CONSTRAINT FK_GUIDE_ON_HOUSING FOREIGN KEY (housing_id) REFERENCES book.housing (id);