CREATE TABLE book.profile
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    phone_number     VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255),
    full_name        VARCHAR(255),
    profile_picture  VARCHAR(255),
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

ALTER TABLE book.profile
    ADD CONSTRAINT uc_profile_email UNIQUE (email);

ALTER TABLE book.profile
    ADD CONSTRAINT uc_profile_phonenumber UNIQUE (phone_number);