CREATE TABLE book.question
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at  TIMESTAMP WITHOUT TIME ZONE,
    name              VARCHAR(255)                            NOT NULL,
    possible_values   JSONB                                   NOT NULL,
    display_order     INTEGER                                 NOT NULL,
    active            BOOLEAN DEFAULT TRUE                    NOT NULL,
    multiple_response BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

ALTER TABLE book.question
    ADD CONSTRAINT uc_question_displayorder UNIQUE (display_order);

ALTER TABLE book.question
    ADD CONSTRAINT uc_question_name UNIQUE (name);

INSERT INTO book.question (name, possible_values, display_order, active, multiple_response) VALUES ('ALREADY_SEEN_BOOK', '{"values":["YES", "NO", "PHYSICAL"]}', 1, TRUE, FALSE);
INSERT INTO book.question (name, possible_values, display_order, active, multiple_response) VALUES ('TEST_MULTIPLE', '{"values":["YES_A", "YES_B", "YES_C"]}', 2, TRUE, TRUE);